### ISSUE TITLE
Will not open if summary data is not present

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everviz#172]
Everviz did not start after an everest run which did not have summary data, the run in question was: math_func -> minimal

**Comment by verveerpj** [comment]
It worked fine for me. I did have to de `everest export config_minimal.yml` first, it did not export the csv file by itself, that seems to be new behaviour. Is it a bug?

Everviz plotted all optimization data properly and reported that there was not summary data for the relevant plots, so working as intended.

This was tested on the main versions for Everest and Everviz, maybe the bug was seen on an older release?

**Comment by oyvindeide** [comment]
That might seem like a bug, yes, but why did that happen for this case and not `egg` I wonder?
