### ISSUE TITLE
Add function doc strings

### ISSUE THREAD

**Issue by oyvindeide** [equinor/everviz#48]
I think we should have function doc strings and be better at adding developer documentation, and would like to remove this: 

https://github.com/equinor/everviz/blob/fe8bb25cd5588e4ff10793398f6b092bff86500b/.pylintrc#L71

Just some basic intent so it´s easy to maintain. Maybe we could drop it for tests?

**Comment by verveerpj** [comment]
:+1: 
However, may I make a suggestion? Maybe we can agree on using autodoc with the napoleon extension: 

https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

I personally favor the Google style, which is very natural to read, but it still renders well with autodoc in the sphinx docs. In visual code studio I use an extension that inserts a template if you start a docstring with `""""`, which makes it really easy to write the correct doc format.

However, you don't want to document every little local function... But I am sure pylint has some facility to deal with that, maybe it skips functions that start with an underscore, like autodoc does?

**Comment by DanSava** [comment]
I think it is a good idea to document classes but when it comes to documenting functions I am more in favor of writing self-documenting code. If we need to write extensive documentation for a function it means that what the function is supposed to do is unclear hence the need for the documentation and it should be redesigned. 

I read some time ago and I found it funny and a bit true "function documentation is like the promise of a future lie"

But if both you guys agree function documentation is needed I comply and start writing documentation for functions.

**Comment by verveerpj** [comment]
I agree with you, to some extent, about the self-documenting code, but I think this is mostly true for comments. If you can read the code and understand how it does it, you do not need comments. (I do not fully subscribe to this philosophy, but if it works out, its fine by me.)

However, this is not true for for doc-strings, those are not comments. These should describe shortly what the function does, and what its arguments are, so that you have developer documentation, on how to use the function, not how it is implemented. Obviously, you only want/need those for functions that somebody may use, not local functions. That is basically the same as documenting public members of a class.

**Comment by verveerpj** [comment]
But after a good night of sleep: Do we need developer documentation for this? Its not like it is a library of functions that anybody going to re-use... So, it might be overkill.

**Comment by oyvindeide** [comment]
We probably don´t need that much developer documentation, and I´m not proposing putting in a lot of documentation, perhaps only a sentence describing the purpose of each function. While arguments could be good, they tend to be much faster neglected and outdated than the intent of the function, so maybe not adding that at all. We should of course strive to write self documenting code, so if you disagree with this I´m fine with closing this issue.

**Comment by verveerpj** [comment]
:+1:

**Comment by DanSava** [comment]
> While arguments could be good, they tend to be much faster neglected and outdated than the intent of the function, so maybe not adding that at all.

I agree and also I agree with writing a description of the purpose of each function
